source "https://rubygems.org"

gem "jekyll", "~> 3.9.0"

gem "minima", "~> 2.5"


gem "github-pages", "~> 215" , group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.15.1"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
  gem "webrick"
end

gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

